### ISSUE TITLE
Need to improve frame rate

### ISSUE THREAD

**Issue by FazeelUsmani** [gilescope/dotsamaworld#33]
I tried running this app on a MacBook pro-2019 with 16 GB RAM and 2.6GHz 6-Core Intel Core i7 and found the frame rate is pretty low and it's taking more time to load the blocks, transactions and bridges. It would be great to fasten the frame rate by loading a smaller dataset or get the crate count down from 680.

**Comment by gilescope** [comment]
The dyn branch has about 530 dependencies now. Interestingly the date picker brings in about 100 dependencies. Guessing it's pulling in a different version of egui...

**Comment by gilescope** [comment]
It's now using about 250 deps on the wasm target, and more importantly with the instances changes that have just been merged in the frame rate is significantly improved (+200fps on phones).
